version: "3.9"
services:
  web:
    build: .
    container_name: web
    ports:
      - "7000:7000"
    env_file:
      - ".env.development"
    depends_on:
      - "db"

  db:
    image: postgres:13
    restart: always
    container_name: db
    ports:
      - "15432:5432"
    env_file:
      - ".env.development"